version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"  # Maps port 8000 on your host to port 80 in the container
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=auth_system
    depends_on:
      - localhost
      

  localhost:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=auth_system
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Uncomment if you want to access MySQL from outside Docker

volumes:
  mysql_data:
